import './globals.css';
import Navbar from "./components/navigation/Nav";
import {Footer} from './components/Footer';
import {Hero} from './components/Hero';
import { ProductsComponent } from './components/Products';

export const metadata = {
  title: 'Dina favoritdrinkar',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="sv">
      <body>
        <Navbar />
        {children}
        <Hero/>
        
        
        <ProductsComponent />
        <Footer/>
      </body>
    </html>
  )
}






